name: lovebirds_app
description: Lovebirds is a premium dating app designed for meaningful connections and authentic relationships. Featuring smart matching, real-time messaging, and secure user verification for users seeking love and companionship.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.2.0+20

environment:
  sdk: ^3.7.2
#  sdk: '>=3.0.3 <4.0.0'
#dart run change_app_package_name:main com.lovebirds.app

dependencies:
  flutter:
    sdk: flutter

  get: ^4.7.2
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  dio: ^5.8.0+1
  shimmer: ^3.0.0
  intl: ^0.20.2

  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2
  flutter_feather_icons: ^2.0.0+1
  sqflite: ^2.4.2
  google_fonts: ^5.1.0
  flutx: ^0.2.0-rc.2
  flutter_staggered_grid_view: ^0.7.0
  fluttertoast: ^8.2.12
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  permission_handler: ^12.0.0+1
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  path_provider: ^2.1.5
  change_app_package_name: ^1.5.0
  chewie: ^1.11.3
  video_player: ^2.9.5
  flutter_rating_bar: ^4.0.1
  keep_screen_on: ^4.0.0
  image_picker: ^1.1.2
  file_picker: ^8.3.7
  record: ^6.0.0
  audioplayers: ^5.2.1
  readmore: ^3.0.0
  wakelock_plus: ^1.2.11
  in_app_update: ^4.2.3
  upgrader: ^10.3.0
  package_info_plus: ^8.0.2
  flutter_easyloading: ^3.0.5
  html_editor_enhanced: 2.6.0
  flutter_launcher_icons: ^0.14.4
  reorderable_grid_view: ^2.2.7

  json_annotation: any
  html: any
  flutter_downloader: ^1.11.6
  flutter_local_notifications: ^19.1.0
  onesignal_flutter: ^5.3.0
  #  firebase_core: ^3.13.0
  #  internet_connection_checker: ^3.0.1
  country_code_picker: ^3.3.0
  flutter_html: ^3.0.0
  easy_image_viewer: ^1.2.0
  overlay_support: any
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true

  #  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

dependency_overrides:
  intl: any
  http: any
  google_fonts: any
  provider: any
  nested: any

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/no_image.png
